### ISSUE TITLE
Addon beamup deployment issue

### ISSUE THREAD

**Issue by MrMonkey42** [Stremio/stremio-addon-sdk#242]
Hi team,

I created an Addon called Debrid Search and when deployed using beamup, the deployment was successful without any errors. But the addon URL is not functioning - [https://68d69db7dc40-debrid-search.baby-beamup.club](https://68d69db7dc40-debrid-search.baby-beamup.club). Could you check and let me know what could be the issue?

Github repo - [https://github.com/MrMonkey42/stremio-addon-debrid-search/](https://github.com/MrMonkey42/stremio-addon-debrid-search/)

Deployment logs after running `beamup`:

```
-----> Shutting down old containers in 60 seconds
       68f04fab22e00fc45eba8ce9496bb2af442ca78771c0766127cf8503c7173aa7
=====> Application deployed:
       http://68d69db7dc40-debrid-search.baby-beamup.club

To a.baby-beamup.club:68d69db7dc40/debrid-search
 + 0fb8004...e3da0b1 HEAD -> master (forced update)
Project URL: 68d69db7dc40-debrid-search.baby-beamup.club
```

`cat beamup.json`:
```
{
    "projectName": "debrid-search",
    "lastCommit": "e3da0b1"
}
```

`beamup logs`:
```
2023-10-15T16:11:43.143181347Z app[web.1]:
2023-10-15T16:11:43.143235015Z app[web.1]: > stremio-debrid-search@0.1.2 start
2023-10-15T16:11:43.143245038Z app[web.1]: > node server.js
2023-10-15T16:11:43.143251886Z app[web.1]:
2023-10-15T16:11:44.154843291Z app[web.1]: HTTP addon accessible at: http://127.0.0.1:5000/manifest.json
```

**Comment by mhdzumair** [comment]
I'm also facing server issue since last two days. Today, I'm unable to the deployment through `beamup deploy` or `git push beamup main:master` 

Stremio team, please fix the issues. Getting more complaints from add-on users.

**Comment by mhdzumair** [comment]
`beamup deploy` hang on forever.  but i can see some log errors when i try `beamup config` 

```
/usr/lib/node_modules/beamup-cli/node_modules/ssh2/lib/client.js:695
        var err = new Error('Timed out while waiting for handshake');
                  ^

Error: Timed out while waiting for handshake
    at Timeout._onTimeout (/usr/lib/node_modules/beamup-cli/node_modules/ssh2/lib/client.js:695:19)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  level: 'client-timeout'
}

Node.js v18.18.2
```

**Comment by mhdzumair** [comment]
Sorry to ping you @jaruba. But I appreciate any help you can provide.

**Comment by mhdzumair** [comment]
Update: Now im able to deploy through `beamup deploy` but the swarm refresh is not working. here is the logs. 

```
Deploying to 882b9915d0fe-mediafusion.baby-beamup.club
******************************************************************************
* WARNING !!!                                                                *
*                                                                            *
* Unauthorized access strictly prohibited.                                   *
*                                                                            *
* Usage of this system may be monitored and recorded by system personnel.    *
*                                                                            *
* Anyone using this system expressly consents to such monitoring and is      *
* advised that if such monitoring reveals possible evidence of criminal      *
* activity, system personnel may provide the evidence from such monitoring   *
* to law enforcement officials.                                              *
*                                                                            *
* Individuals using this equipment without authority, or in excess of their  *
* authority, are subject to legal action.                                    *
*                                                                            *
******************************************************************************
Enumerating objects: 155, done.
Counting objects: 100% (155/155), done.
Delta compression using up to 8 threads
Compressing objects: 100% (122/122), done.
Writing objects: 100% (124/124), 165.39 KiB | 4.35 MiB/s, done.
Total 124 (delta 72), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (72/72), completed with 20 local objects.
-----> Cleaning up...
-----> Building 882b9915d0fe-mediafusion from herokuish...
-----> Adding BUILD_ENV to build environment...
-----> Python app detected
-----> Using Python version specified in runtime.txt
-----> Using cached install of python-3.11.6
-----> Installing pip 23.2.1, setuptools 68.0.0 and wheel 0.41.0
-----> Installing dependencies with Pipenv 2023.7.23
       Loading .env environment variables...
       Installing dependencies from Pipfile.lock (385fe3)...
-----> Installing SQLite3
-----> Discovering process types
       Procfile declares types -> web
-----> Releasing 882b9915d0fe-mediafusion (dokku/882b9915d0fe-mediafusion:latest)...
-----> Deploying 882b9915d0fe-mediafusion (dokku/882b9915d0fe-mediafusion:latest)...
-----> App Procfile file found (/home/dokku/882b9915d0fe-mediafusion/DOKKU_PROCFILE)
       DOKKU_SCALE declares scale -> web=1
=====> Processing deployment checks
       No CHECKS file found. Simple container checks will be performed.
       For more efficient zero downtime deployments, create a CHECKS file. See http://dokku.viewdocs.io/dokku/deployment/zero-downtime-deploys/ for examples
-----> Attempting pre-flight checks (web.1)
       Waiting for 10 seconds ...
       Default container check successful!
-----> Running post-deploy
-----> Configuring 882b9915d0fe-mediafusion.baby-beamup.club...(using built-in template)
-----> Creating http nginx.conf
       Reloading nginx
-----> Renaming containers
       Found previous container(s) (6d0d381c2cbf) named 882b9915d0fe-mediafusion.web.1
       Renaming container (6d0d381c2cbf) 882b9915d0fe-mediafusion.web.1 to 882b9915d0fe-mediafusion.web.1.1697612778
       Renaming container (5f7440d9bbf9) eloquent_ramanujan to 882b9915d0fe-mediafusion.web.1
remote: + APP=882b9915d0fe-mediafusion
remote: + docker tag dokku/882b9915d0fe-mediafusion:latest localhost:5000/dokku/882b9915d0fe-mediafusion:latest
remote: + docker push localhost:5000/dokku/882b9915d0fe-mediafusion:latest
The push refers to repository [localhost:5000/dokku/882b9915d0fe-mediafusion]
804fde688128: Preparing
53fd92697819: Preparing
c11d1b6a92a6: Preparing
87197be4f1be: Preparing
cf0a5e4dedf3: Preparing
d0ae8bf5705d: Preparing
896efdbbe06a: Preparing
e3f21d5d528e: Preparing
b6477286a254: Preparing
1697a5791d37: Preparing
3ae63c5341ad: Preparing
a52cb26790ac: Preparing
690c97264593: Preparing
a880b0661461: Preparing
07ec26a9e070: Preparing
6c3e7df31590: Preparing
d0ae8bf5705d: Waiting
896efdbbe06a: Waiting
e3f21d5d528e: Waiting
b6477286a254: Waiting
1697a5791d37: Waiting
3ae63c5341ad: Waiting
a52cb26790ac: Waiting
690c97264593: Waiting
a880b0661461: Waiting
07ec26a9e070: Waiting
6c3e7df31590: Waiting
87197be4f1be: Pushed
804fde688128: Pushed
896efdbbe06a: Layer already exists
53fd92697819: Pushed
e3f21d5d528e: Layer already exists
b6477286a254: Layer already exists
1697a5791d37: Layer already exists
3ae63c5341ad: Layer already exists
a52cb26790ac: Layer already exists
690c97264593: Layer already exists
a880b0661461: Layer already exists
07ec26a9e070: Layer already exists
6c3e7df31590: Layer already exists
cf0a5e4dedf3: Pushed
d0ae8bf5705d: Pushed
c11d1b6a92a6: Pushed
latest: digest: sha256:1188b28b27a73ad420d03c2a26e61be60cef1b93018521adedb7bfdd52ae4cb5 size: 3664
remote: + ssh -T -i /home/dokku/.ssh/id_ed25519_sync beamup@stremio-beamup-swarm-0
remote: ******************************************************************************
remote: * WARNING !!!                                                                *
remote: *                                                                            *
remote: * Unauthorized access strictly prohibited.                                   *
remote: *                                                                            *
remote: * Usage of this system may be monitored and recorded by system personnel.    *
remote: *                                                                            *
remote: * Anyone using this system expressly consents to such monitoring and is      *
remote: * advised that if such monitoring reveals possible evidence of criminal      *
remote: * activity, system personnel may provide the evidence from such monitoring   *
remote: * to law enforcement officials.                                              *
remote: *                                                                            *
remote: * Individuals using this equipment without authority, or in excess of their  *
remote: * authority, are subject to legal action.                                    *
remote: *                                                                            *
remote: ******************************************************************************
remote: bash: /home/beamup/beamup-sync-swarm.sh-disabled: No such file or directory
To a.baby-beamup.club:882b9915d0fe/mediafusion
 ! [remote rejected] HEAD -> master (pre-receive hook declined)
error: failed to push some refs to 'a.baby-beamup.club:882b9915d0fe/mediafusion'
Project URL: 882b9915d0fe-mediafusion.baby-beamup.club
```

**Comment by mhdzumair** [comment]
Update: The service is up again and work as expected. Thanks stremio

**Comment by mhdzumair** [comment]
Update: seems like the server storage full. 

```
remote: (node:10291) UnhandledPromiseRejectionWarning: Error: ENOSPC: no space left on device, write
remote:     at Object.writeSync (fs.js:679:3)
remote:     at Object.writeFileSync (fs.js:1393:26)
remote:     at /usr/local/bin/beamup-sync-swarm:168:5
remote:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
remote: (node:10291) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
remote: (node:10291) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
remote: top-level object must be a mapping
```

**Comment by mhdzumair** [comment]
we can close this.
